name: Peloton
on:
  schedule:
    - cron: "50 02 * * *"

  push:
    branches:
      - "peloton_GHA"

jobs:
  update_peloton_project_board:
    name: "Update Peloton Project Board"

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.AUTH_APP_ID }}
          private_key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}

      - name: "Add issue 4000"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api graphql -f query='
            mutation {
              addProjectV2ItemById(input: {projectId: "PVT_kwDOABU7f84ALhAI" contentId: "MDU6SXNzdWU4MDcxMTY2Mzg="}) {
                item {
                  id
                }
              }
            }'
