name: Peloton
on:
  schedule:
    - cron: "50 02 * * *"

  push:
    branches:
      - "peloton_GHA"

jobs:
  Update Peloton Project Board:
    steps:
      name: "Update Peloton Project Board"

      runs-on: ubuntu-latest

      defaults:
        run:
          shell: bash -l {0}

      steps:
        run: |
          gh api graphql -f query='
            mutation {
              addProjectsV2ItemById(input: {projectId; "PVT_kwDOABU7f84ALhAI" contentId: "MDU6SXNzdWU4MDcxMTY2Mzg="}) {
                item {
                  id
                }
              }
            }'
